services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mi-app:optimizado
    container_name: mi-app-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/miapp
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mi-app-mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: miapp
    restart: unless-stopped

volumes:
  mongo-data:

