
services:
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - micro_net

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGO_URL=mongodb://db:27017/blog
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - micro_net

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - micro_net

  db:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - micro_net

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - micro_net

volumes:
  mongo_data:
  redis_data:

networks:
  micro_net:
    driver: bridge
